baseURL = "https://personalblogst.z22.web.core.windows.net/"
languageCode = "de-at"
title = "Maria Strasser - Software Development Blog"
theme="liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Über mich"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "Kontakt"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Über mich"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Kontakt"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Startseite"
# Meta data
description = "This is meta description"
author = "Maria Strasser"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
#mobile = "0124857985320"
email = "kontakt@maria-strasser.at"
location = "Linz, Austria"
hpage = "www.maria-strasser.at"
# copyright
#copyright = "| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Newsletter abonnieren"
content = "Über neuen Blog-Artikel informiert werden"

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/strasser_maria"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/mstrasser22"